### ISSUE TITLE
Atualizar form Nova Matriz de Pontos Críticos (ambiente migração) no ambiente de produção

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#102]

**Comment by r-guimaraes** [comment]
@lvilarins já foi alterada há umas 3 semanas atrás. Houve novas alterações nesse período?

**Comment by lvilarins** [comment]
Sim. Tirei o Ponto Crítico 7

**Comment by lvilarins** [comment]
E o que vc tá fazendo trabalhando hoje e a essa hora? Vai curtir a vida...
