### ISSUE TITLE
Criar Mês/Ano de ocorrência - como foi feito em Indicadores Hospital Geral - para os seguintes forms: Avaliação de oficina local, Avaliação de grupo, Relatório de oficina, Videoconferência, Memória de reunião

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#103]

**Comment by lvilarins** [comment]
Não aparecem para mim. O modelo é o mesmo que foi feito no form Indicadores Hospital Geral

**Comment by andre2ar** [comment]
Eu já tinha feito mas por algum motivo perdeu, está no migração

**Comment by lvilarins** [comment]
Oi André. Tanto na produção quanto na migração não aparece para mim. Só vejo as mesmas categorias: Campo de Atuação; Fase; Nome; Data; Criação; Autor; Excluir. Não aparece Mês/Ano de ocorrência.

**Comment by andre2ar** [comment]
![Captura de tela de 2019-03-18 09-03-17.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5979dd7cb329eb001afb8bdd/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2723dd5b065ee1a3b5156424eaf5c595856e0ebc969f9ec6923ce4e01ffd43c0b22c06c17a9b0d31eed02b9208b4ed7e5ef8b1993be2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee44f5ca5133066e475337c55d9.png)

**Comment by andre2ar** [comment]
http://migracao.redehumanizasus.net/relatorio_oficina/relatorio-de-oficina-15/

**Comment by lvilarins** [comment]
Não é dentro do formulário,  é nã parte de fora.
Abra o de Indicadores Hospital Geral e depois abra qualquer outro que citei. Estão diferentes. 

P.S.: não consigo colocar uma imagem aqui como você fez. Você sobe uma figura ou cola o print screen?

**Comment by r-guimaraes** [comment]
@lvilarins teste novamente em migração, por favor

**Comment by lvilarins** [comment]
Testado. Ok! Pode subir pra produção apra eles voltarem a preencher

**Comment by lvilarins** [comment]
Rodrigo, falta ainda 

1.
Criar "Mês/Ano de criação" para:
Indicadores Materno-Infantil;
Indicadores CAPS;
INdicadores da Atenção Básica;

2. Subir isso pra produção.

**Comment by r-guimaraes** [comment]
@lvilarins verifique em produção por favor

**Comment by lvilarins** [comment]
Resolvida!
