### ISSUE TITLE
Gerar um gráfico de exmplo de Indicadores Hospital Geral para Alagoas

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#104]

**Comment by andre2ar** [comment]
![Captura de tela de 2019-03-12 14-58-14.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5979dd7cb329eb001afb8bdd/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2723dd5b065ee103b505b424ba45c595b56e0ebc969f9ec6923ce4e01ffd43c0b22c06c17a9b0d31eed02b9208b4ed7e5ef8b1993be2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee44f51a5103360ee74357c55d9.png)

**Comment by lvilarins** [comment]
Precisamos mudar a escala desse gráfico. Talvez colocar até 5 (0, 1, 2, 3, 4, 5) no exio Y.
E tirar as casas decimais (por exmplo, 4 e não 4,000)

**Comment by andre2ar** [comment]
Mudei para exibir somente inteiros no eixo Y, porém definir um valor maximo para Y acho que não é uma boa ideia. Cada grafico pode ter um maximo diferente e a linha tende a ficar mais curva conforme novos dados são adicionados, podendo assim serem visualizados mais facilmente.

**Comment by lvilarins** [comment]
OK.
