### ISSUE TITLE
Modificar a composição do gráfico do form Avaliação de Grupo

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#107]
Há 7 questões no gráfico do formulário.
A sétima questão "Avaliação do grupo pelo consultor" deve permanecer no formulário, mas não deve fazer parte do gráfico.

**Comment by andre2ar** [comment]
![6.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5979dd7cb329eb001afb8bdd/125516c66e82c728ace21e0d46bed6d6619291a685ecbc57e607b2c1284221252852f67371d4e17bec122b500d0c1dad140b0956e0ebcb7af8e2632dd3165eafc3674d75c13710a9bd8019b908b2268a4683beaec7.png)

**Comment by andre2ar** [comment]
Onde ele gera até o 7? Fiz esse teste e gerou só até o 6.

**Comment by lvilarins** [comment]
Na verdade, é para tirar o 7º gráfico do relatório. Ele fica no formulário, mas não sai no relatório.

**Comment by andre2ar** [comment]
Mas já não tem 7 gráficos no relatório, é pra continuar sem sair ele?

**Comment by lvilarins** [comment]
No relatório não é para sair o 7º gráfico. Só os 6 primeiros. No formulário, podem continuar as 7 perguntas.
