### ISSUE TITLE
Atualização do form Indicadores Hospital Geral

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#108]
No ambiente de migração incluí 3 novas questões sobre o levantamento de estatísticas. São elas:
- Levanta estatística de entradas reguladas pelo SAMU?
- Levanta estatística de entradas por demandas espontâneas?
- Levanta estatística de entradas referenciadas?

As três têm uma questão "informe o número" subordinada a elas.

**Comment by lvilarins** [comment]
As observações feitas acima não aparecem no Form. Essas três perguntas foram criadas: Levanta estatística de entradas reguladas pelo SAMU?
Levanta estatística de entradas por demandas espontâneas?
Levanta estatística de entradas referenciadas?

E a cada uma delas deve ser subordinada a questão "Informe o número:"

O modelo no ambiente de migração está salvo como "Indicadores". Eu não tenho como subordinar uma questão a outra, pois precisa de programação fora do painel que manipulo, mas o modelo já está todo construído nesse "Indicadores" lá na migração.

**Comment by r-guimaraes** [comment]
@lvilarins, o @andre2ar fez essas modificações no ambiente de migração.

@andre2ar , manda o link pra ela por favor

**Comment by andre2ar** [comment]
@lvilarins http://migracao.redehumanizasus.net/indicadores/indicadores-hospital-geral-12/

**Comment by lvilarins** [comment]
Ok. Atualizei este arquivo no migração para o modelo correto. Agora pode subir na produção.
