### ISSUE TITLE
Matriz de Cenário: após a questão "1.1.5.2 Para quais Unidades de Saúde? ", tem que abrir um campo "Quais" (questão aberta texto) quando for marcado "Outras". E tem que ser obrigatória

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#117]

**Comment by r-guimaraes** [comment]
@lvilarins Essa questão já existe dessa maneira no formulário. Porém, pra aparecer, é necessário seguir um fluxo mínimo:
 --> `1.1.5 Existe listagem de ações/ofertas de serviços para os usuários (carta de serviço)? *`
--------> Escolher a segunda, terceira, ou quarta opções.
----------------> Marcar `Outras` em `1.1.5.2 Para quais Unidades de Saúde? *`

**Comment by r-guimaraes** [comment]
Havia uma pergunta `1.1.5.2 Para quais Unidades de Saúde? ` - não sei como foi parar lá. Estava duplicada, fora do lugar, e sem a regra. Então a removi

**Comment by lvilarins** [comment]
Ok
