### ISSUE TITLE
Indicadores Materno-Infantil e Indicadores CAPS: Não tem a coluna Mês/Ano de Ocorrência na visualização do conjnto dos formulários respondidos e não estão gerando gráfico

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#119]
Isso pode estar ocorrendo também com Indicadores Hospital Geral e Indicadores da Ateção Básica, mas eu ainda não verifiquei

**Comment by r-guimaraes** [comment]
@lvilarins A coluna agora já aparece na visualização do conjunto

**Comment by r-guimaraes** [comment]
- [ ] Gerar gráfico geral das respostas
