### ISSUE TITLE
Aprimorar filtros para "Fase"

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/acolhesus-forms#22]
Quando filtramos os formulários por fase, devem retornar apenas aqueles cuja fase é a selecionada.

Atualmente ele filtra corretamente, trazendo "nenhum resultado" para os forms que não sáo da fase escolhida.

Porém essa maneira deixa mais claro para o usuário

**Comment by lvilarins** [comment]
Ok. Validado.
