### ISSUE TITLE
Verificar permissões e abertura na single do form

### ISSUE THREAD

**Issue by leogermani** [medialab-ufg/acolhesus-forms#6]
Se pessoa não tiver permissão pra ver, não ver nada

Se tiver permissão só pra ver, mas não editar, só vê as respostas

Se o form tiver sido fechado pela PNH, só vê respostas

**Comment by leogermani** [comment]
falta fazer aqueles botões parar de funcionar

**Comment by r-guimaraes** [comment]
Ve se nao eh o que tah no commit de sexta de manha
