### ISSUE TITLE
Erros na saída da matriz de pontos críticos

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/acolhesus-forms#87]
- [ ] Saída do Formulário não exibe a categoria das causas
- [x] Campo diretriz/dispositivos não sai no relatório

**Comment by lvilarins** [comment]
É preciso consertar este erro com urgência

**Comment by r-guimaraes** [comment]
@andre2ar prioriza essa issue por favor

**Comment by andre2ar** [comment]
O Caldera não separa as informações por categoria, a label que indica a categoria de um dado não é atrelada a esse dado não sendo possivel indicar qual a label do dado.

**Comment by lvilarins** [comment]
Mas como para as outras questões deu certo?
No form tem "Ponto Crítico" e o espaço para responder; "Caracterização" e o espaço para responder; "Diretrizes" e o espaço para responder => para cada uma delas sai uma resposta separada no relatório.

O mesmo deve ser possível fazer para as Causas. Porque tem:
"Gestão de Pessoas e Qualificação Profissional
Causas do Ponto Crítico 1 *" e espaço para responder;

"Gestão de Materiais e Insumos
Causas do Ponto Crítico 1 *" e espaço para responder

E, assim, por diante.

**Comment by andre2ar** [comment]
Os outros dados estavam estruturados de  forma diferente. Esses vem assim:

[Label, Label, Label, Dado, Dado, Label, Label, Dado, Dado]

Não é possível identificar a qual dado pertence uma label,  elas vem misturadas aos dados e sem qualquer indicativo de qual dados são, o que na visão do Caldera está correto já que não foram criadas em conjunto aos dados e estão apenas ordenadas no formulário de forma a fazer sentido ao usuário. No entanto essa ordem não é mantida quando os dados são recuperados do banco de dados.

Uma forma de resolver de resolver o problema seria modificando o formulário adicionando a label junto ao dado, mas isso também pode gerar outros problemas caso seja necessário mudar o formulário novamente.

**Comment by lvilarins** [comment]
Entendo. Mas como elas não começaram a preencher este formulário, acho melhor modificarmos o formulário "adicionando a label junto ao dado" e, se eles mexerem novamente no formulário no futuro, a gente cria outro formulário e abandona este.

**Comment by r-guimaraes** [comment]
@lvilarins teste de novo por favor

**Comment by lvilarins** [comment]
Corrigido!
