### ISSUE TITLE
Testar Webnários da maneira como está

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/acolhesus-forms#88]
Utilizando a sala de eventos

**Comment by lvilarins** [comment]
Primeiro teste conluído e sugestões aprovadas pelo Ministério (7/3).
A equipe CGPNH criou um canal da Humanização e fará uma transmissão ao vivo para novo teste na próxima semana.
É preciso criar a funcionalidade dos comentários da mesma forma que é feito o "histórico" nos fomrulários do AcolheSUS.
