### ISSUE TITLE
Criar relatório  (geral e individual) para relatorio de oficinas, memoria de reuniao, e videoconferencias

### ISSUE THREAD

**Issue by r-guimaraes** [medialab-ufg/acolhesus-forms#89]

**Comment by lvilarins** [comment]
Ótimo, André!
É possível colocar os textos como "justificados"? Porque eles estão "alinhados à esquerda"

**Comment by lvilarins** [comment]
Os textos no relatório não estão "justificados". Estão "alinhados à esquerda".

**Comment by lvilarins** [comment]
Os relatórios permanecem alinhados à esquerda e não justificados. É possível mudar a formatação para "justificada"?

**Comment by andre2ar** [comment]
![Captura de tela de 2019-03-18 09-12-54.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5979dd7cb329eb001afb8bdd/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2723dd5b065ee1a3b5156424fae5c5d5b56e0ebc969f9ec6923ce4e01ffd43c0b22c06c17a9b0d31eed02b9208b4ed7e5ef8b1993be2f39f5c9de116a415841c3aa1f27aa8b4acf52f74ee44f5ca512376ae572377455d9.png)

**Comment by andre2ar** [comment]
O texto ficou dessa forma, não é assim?
