### ISSUE TITLE
Erro: Campo de atuação (AC) e Fase (I) aparecem respondidos como default em alguns forms

### ISSUE THREAD

**Issue by lvilarins** [medialab-ufg/acolhesus-forms#93]
- Indicadores Materno-Infantil
- Indicadores CAPS
- Indicadores Hospital Geral
- Indicadores da Atenção Básica
- Avaliação de Grupo
- Avaliação de Oficina Local
- Relatório de Oficina
- Videoconferências
- Memória de Reunião

**Comment by lvilarins** [comment]
No teste continua aparecendo Ac e Fase I em todos os formulários citados

**Comment by r-guimaraes** [comment]
@lvilarins teste de novo por favor

**Comment by lvilarins** [comment]
Validado!
